- name: Configuration de base du serveur VPS
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installer des paquets essentiels
      apt:
        name:
          - curl
          - git
          - ufw
        state: present

    - name: Installer Docker
      shell: |
        curl -fsSL https://get.docker.com | sh
        systemctl start docker
        systemctl enable docker

    - name: Configurer UFW pour autoriser le port 22 (SSH) et 3000
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22
        - 3000

    - name: Activer UFW
      ufw:
        state: enabled