### Configuration de nginx sur la machine Vagrant (Ubuntu/Debian)
- name: Configuration de Nginx sur la machine Vagrant
  hosts: MACHINE_VAGRANT
  become: yes
  tasks:
    # Supprimer la configuration par défaut de Nginx
    - name: Supprimer la configuration par défaut de Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    # Créer le fichier de configuration pour Grafana
    - name: Créer le fichier de configuration pour Grafana
      file:
        path: /etc/nginx/sites-available/grafana
        state: touch
        mode: '0644'

    # Ajouter ou remplacer la configuration Nginx pour Grafana
    - name: Ajouter la configuration Nginx pour Grafana
      blockinfile:
        path: /etc/nginx/sites-available/grafana
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          server {
              listen 80;
              server_name {{ inventory_hostname }};

              location / {
                  proxy_pass http://127.0.0.1:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    # Créer un lien symbolique pour activer la configuration Grafana
    - name: Activer la configuration Grafana
      file:
        src: /etc/nginx/sites-available/grafana
        dest: /etc/nginx/sites-enabled/grafana
        state: link

    # Vérifier la syntaxe de Nginx
    - name: Vérifier la configuration Nginx
      command: nginx -t

    # Redémarrer Nginx
    - name: Redémarrer le service Nginx
      service:
        name: nginx
        state: restarted

### Configuration de Nginx sur la machine VPS (Red Hat/CentOS)
- name: Configuration dynamique de Nginx sur la machine VPS
  hosts: MACHINE_VPS
  become: yes
  tasks:
    - name: Sauvegarder et désactiver la configuration par défaut de Nginx
      command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
      args:
        removes: /etc/nginx/conf.d/default.conf

    - name: Créer le fichier de configuration pour JuiceShop
      file:
        path: /etc/nginx/conf.d/juice.conf
        state: touch
        mode: '0644'

    # Ajouter ou remplacer la configuration Nginx pour JuiceShop
    - name: Ajouter la configuration Nginx pour JuiceShop
      blockinfile:
        path: /etc/nginx/conf.d/juice.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          server {
              listen 80;
              server_name {{ inventory_hostname }};

              location / {
                  proxy_pass http://127.0.0.1:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    # Vérifier la syntaxe de Nginx
    - name: Vérifier la configuration Nginx
      command: nginx -t

    # Redémarrer Nginx
    - name: Redémarrer le service Nginx
      service:
        name: nginx
        state: restarted