- name: Installer curl
  hosts: all
  become: yes
  tasks:
    - name: Installer curl sur Debian/Ubuntu
      apt:
        name:
          - curl
        state: present
      when: ansible_os_family == "Debian"

    - name: Installer curl sur CentOS/Red Hat
      yum:
        name:
          - curl
        state: present
      when: ansible_os_family == "RedHat"