- name: Installer Python sur toutes les machines
  hosts: all
  gather_facts: False
  become: yes
  tasks:
    - name: Installer Python sur Ubuntu/Debian
      raw: |
        apt-get update -y
        apt-get install -y python3
      when: ansible_os_family == "Debian"

    - name: Installer Python sur CentOS/RedHat
      raw: |
        yum install -y python3
      when: ansible_os_family == "RedHat"