- name: Install Python
  gather_facts: False # python n'est pas encore installé
  hosts: all
  become: True
  tasks:
    - name: Install Python using raw module
      raw: |
        apt-get update
        apt-get install -y python3
