- name: Installer git
  hosts: all
  become: yes
  tasks:
    - name: Installer git sur Debian/Ubuntu
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Installer git sur Red Hat/CentOS
      yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"