- name: Mettre à jour les paquets du système
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour les paquets sur Ubuntu/Debian
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Mettre à jour les paquets sur CentOS/Red Hat
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"